### ISSUE TITLE
Following the install instructions does not work

### ISSUE THREAD

**Issue by andyfensham** [NetCoreApps/NorthwindCrud#3]
Followed the instruction to download and run this, but are getting the following errors as attached.
![Snag_de94a5e](https://user-images.githubusercontent.com/5065306/121853782-a4437100-ccf1-11eb-87f6-dc3b439a6850.png)

I am running Version 5.1.20 of x tool, 
Version 5.111 of servicestack
Framework 5.0.7
OS: Windows

**Comment by mythz** [comment]
Whenever you have missing method/type exceptions using the pre-release packages on MyGet you'll need to [clear out your NuGet cache](https://docs.servicestack.net/myget#redownloading-myget-packages) to download the latest version of each package:

    $ nuget locals all -clear
