### ISSUE TITLE
Installing using instructions does not work

### ISSUE THREAD

**Issue by andyfensham** [NetCoreApps/NorthwindCrud#4]
``
$ x download NetCoreApps/NorthwindCrud
$ cd NorthwindCrud
$ dotnet run
![Snag_13a8b50c](https://user-images.githubusercontent.com/5065306/122034794-2905bc00-cdd2-11eb-9f26-eadef8d00e74.png)

``

**Comment by mythz** [comment]
Missing Type/Method Exceptions using pre-release packages is same issue as: https://github.com/NetCoreApps/BookingsCrud/issues/1

Clear NuGet Packages Cache:

    $ nuget locals all -clear

Then download & restore to get the latest pre-release package versions:

    $ x download NetCoreApps/NorthwindCrud -out NorthwindCrud
    $ cd NorthwindCrud
    $ dotnet run

![image](https://user-images.githubusercontent.com/89361/122060975-a9eba480-ce20-11eb-880f-dccf0ac99b5a.png)
